#!/bin/bash
batchSystem="singleMachine"
maxThreads="20"
defaultMemory="8589934592"
jobTree=".downloadedJobTree/"
log="downloadedLog.txt"
maxCpus="250"


export PYTHONPATH=./:${PYTHONPATH}
export PATH=./sonLib/bin:./submodules/jobTree/bin:${PATH}


if [ -d ${jobTree} ]; then 
    rm -rf ${jobTree}
fi

python src/downloadedPipeline.py --save_intermediate --maxThreads=${maxThreads} --batchSystem=${batchSystem} --maxCpus ${maxCpus} --defaultMemory=${defaultMemory} --jobTree ${jobTree} --logLevel DEBUG --stats &> ${log}
